# Generated by Django 5.0.3 on 2024-03-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
