# Generated by Django 5.0.3 on 2024-03-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LojaIntegrada',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp_phone_number', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('doc', models.CharField(max_length=14)),
                ('autorization_token', models.CharField(max_length=200)),
            ],
        ),
    ]
