# Generated by Django 5.0.3 on 2024-03-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Integracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_loja', models.CharField(max_length=100)),
                ('telefone_loja', models.CharField(max_length=20)),
                ('cnpj_cpf_loja', models.CharField(max_length=14)),
                ('autorization_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('status_pagamento', models.CharField(max_length=50)),
                ('status_envio', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuvemshop_app.cliente')),
            ],
        ),
    ]
