# Generated by Django 5.0.3 on 2024-04-04 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LojaIntegrada',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('whatsapp_phone_number', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('doc', models.CharField(max_length=14)),
                ('autorization_token', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
