# Generated by Django 5.0.3 on 2024-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvemshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaintegrada',
            name='whatsapp_phone_number',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
