# Generated by Django 5.0.3 on 2024-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvemshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lojaintegrada',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
