# Generated by Django 5.0.3 on 2024-04-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvemshop_app', '0002_alter_lojaintegrada_whatsapp_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaintegrada',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lojaintegrada',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lojaintegrada',
            name='whatsapp_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
