# Generated by Django 5.0.3 on 2024-04-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvemshop_app', '0002_lojaintegrada_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaintegrada',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
