# Generated by Django 5.0.3 on 2024-04-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuvemshop_app', '0003_alter_lojaintegrada_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lojaintegrada',
            name='doc',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
